name: test-functions

on:
  workflow_dispatch:
    inputs:
      ambiente:
        description: "Ambiente"
        required: true
        default: "DEV"

jobs:
  functions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Contexto básico
      run: | 
        echo "Actor: ${{ github.actor }}"
        echo "Branch: ${{ github.branch }}"
        echo "Run number: ${{ github.run_number}}"

    - name: Startswith | Endswith
      run: |
        ${{ startsWith(github.ref, 'refs/heads/') }}
        echo "Rodando em branch"
    
    - name: contains
      if: ${{ contains(github.ref_name, 'main') }}
      run: echo "Branch contém 'main'"

    - name: format
      run: echo "${{ format('Deploy {0} no ambiente {1}', github.ref_name, inputs.ambiente) }}"

    - name: hashFiles
      env:
        FILE_HASH: ${{ hashFiles('.github/workflows/functions-test.yml')}}
      run: |
        echo "Hash: $FILE_HASH"
